### ISSUE TITLE
CodeResources has no meta file, but it's in an immutable folder. The asset will be ignored.

### ISSUE THREAD

**Issue by rameshporeddy** [bugsnag/bugsnag-unity-performance#79]
### Describe the bug
Unity throwing complile time error after importing the package using UPM

### Steps to reproduce
1. Import package using UPM(am using mac machine)
2. Wait for compilation to complete and see the errors in cosole

### Environment
* BugSnag Performance library version:1.20
* BugSnag Error Monitoring library version (if any):
* Unity version:2020.3.41f
* iOS/Android/macOS/Windows/browser version:Mac v13.4
* simulator/emulator or physical device: Editor
* Initializing bugSnag performance via a Unity GameObject or in code?:NA
* Player Settings:
    * Scripting backend (Mono or IL2CPP):IL2CPP
    * API compatibility level for .NET:2.0
    * Stack Trace level for all error types (None/ScriptOnly/Full):

<details><summary>Error messages:</summary>

```
Asset Packages/com.bugsnag.performance.unity/Runtime/Plugins/MacOS/BugsnagUnityPerformanceMacOS.bundle/Contents/_CodeSignature/CodeResources has no meta file, but it's in an immutable folder. The asset will be ignored.
```
</details>

**Comment by clr182** [comment]
Hi @rameshporeddy 
Apologies about the delay in response time. We have a fix for this issue in [Release v1.3.0](https://github.com/bugsnag/bugsnag-unity-performance/releases/tag/v1.3.0) 
I'm going to close this issue out now, but please let us know if you are seeing any similar issues after upgrading to the latest release.
